Traceback (most recent call last):
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/work/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(1,1)
Q = ax.quiver(0, 0, -L[0,0], -L[1,0], color='r', scale = 100, label = 'reaction force')
mark, = ax.plot(sol.y[0,0], sol.y[1,0], 's', markersize = 20, label = 'com location')
ax.plot(y.y[0], y.y[1], '.')
ax.legend()
ax.set_xlim(-1, 1)
ax.set_ylim(-0.75, 0.75)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [14][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m Q [38;5;241m=[39m ax[38;5;241m.[39mquiver([38;5;241m0[39m, [38;5;241m0[39m, [38;5;241m-[39mL[[38;5;241m0[39m,[38;5;241m0[39m], [38;5;241m-[39mL[[38;5;241m1[39m,[38;5;241m0[39m], color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m, scale [38;5;241m=[39m [38;5;241m100[39m, label [38;5;241m=[39m [38;5;124m'[39m[38;5;124mreaction force[39m[38;5;124m'[39m)
[1;32m      3[0m mark, [38;5;241m=[39m ax[38;5;241m.[39mplot(sol[38;5;241m.[39my[[38;5;241m0[39m,[38;5;241m0[39m], sol[38;5;241m.[39my[[38;5;241m1[39m,[38;5;241m0[39m], [38;5;124m'[39m[38;5;124ms[39m[38;5;124m'[39m, markersize [38;5;241m=[39m [38;5;241m20[39m, label [38;5;241m=[39m [38;5;124m'[39m[38;5;124mcom location[39m[38;5;124m'[39m)
[0;32m----> 4[0m ax[38;5;241m.[39mplot([43my[49m[38;5;241m.[39my[[38;5;241m0[39m], y[38;5;241m.[39my[[38;5;241m1[39m], [38;5;124m'[39m[38;5;124m.[39m[38;5;124m'[39m)
[1;32m      5[0m ax[38;5;241m.[39mlegend()
[1;32m      6[0m ax[38;5;241m.[39mset_xlim([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m1[39m)

[0;31mNameError[0m: name 'y' is not defined
NameError: name 'y' is not defined

