Traceback (most recent call last):
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/work/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.plot(r0.t,r0.y[0],label='0 rad/s')
plt.plot(r3.t,r3.y[0],label='3 rad/s')
plt.plot(r6.t,r6.y[0],label='6 rad/s')
plt.legend()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-9-f18560f0a3fe>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mr0[0m[0;34m.[0m[0mt[0m[0;34m,[0m[0mr0[0m[0;34m.[0m[0my[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m[0mlabel[0m[0;34m=[0m[0;34m'0 rad/s'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mr3[0m[0;34m.[0m[0mt[0m[0;34m,[0m[0mr3[0m[0;34m.[0m[0my[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m[0mlabel[0m[0;34m=[0m[0;34m'3 rad/s'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mr6[0m[0;34m.[0m[0mt[0m[0;34m,[0m[0mr6[0m[0;34m.[0m[0my[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m[0mlabel[0m[0;34m=[0m[0;34m'6 rad/s'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mplt[0m[0;34m.[0m[0mlegend[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'r3' is not defined
NameError: name 'r3' is not defined

