Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

from matplotlib import animation, rc
from IPython.display import HTML

fig, ax = plt.subplots()

ax.set_xlim(( 0, 2))
ax.set_ylim((-0.1, 2))

line, = ax.plot([], [], 's')
quiv, = ax.quiver([],[],[],[])

def init():
    line.set_data([], [])
    quiv.set_UVC([],[])
    return (line,)
    
def animate(i):
    x = np.linspace(0, 1, 100)
    line.set_data(x[i], 0)
    plt.quiver(x[i],0,F[0],F[1])
    return (line,)
    
anim = animation.FuncAnimation(fig, animate, init_func=init,
                               frames=100, interval=20, blit=True)

HTML(anim.to_html5_video())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-53-eca8124aca18>[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0mline[0m[0;34m,[0m [0;34m=[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0;34m[[0m[0;34m][0m[0;34m,[0m [0;34m[[0m[0;34m][0m[0;34m,[0m [0;34m's'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 12[0;31m [0mquiv[0m[0;34m,[0m [0;34m=[0m [0max[0m[0;34m.[0m[0mquiver[0m[0;34m([0m[0;34m[[0m[0;34m][0m[0;34m,[0m[0;34m[[0m[0;34m][0m[0;34m,[0m[0;34m[[0m[0;34m][0m[0;34m,[0m[0;34m[[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     13[0m [0;34m[0m[0m
[1;32m     14[0m [0;32mdef[0m [0minit[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: cannot unpack non-iterable Quiver object
TypeError: cannot unpack non-iterable Quiver object

