Traceback (most recent call last):
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/work/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
upload_imgur.upload_image('./jupyter-main.png')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mupload_imgur[49m[38;5;241;43m.[39;49m[43mupload_image[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m./jupyter-main.png[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/bin/upload_imgur.py:30[0m, in [0;36mupload_image[0;34m(file_path, title, description)[0m
[1;32m     26[0m PATH [38;5;241m=[39m file_path [38;5;66;03m#"A Filepath to an image on your computer"[39;00m
[1;32m     28[0m im [38;5;241m=[39m pyimgur[38;5;241m.[39mImgur(CLIENT_ID, 
[1;32m     29[0m     client_secret [38;5;241m=[39m [38;5;124m'[39m[38;5;124m8953292db6bfd4328ab68327f1efb10013fbdcbc[39m[38;5;124m'[39m)
[0;32m---> 30[0m uploaded_image [38;5;241m=[39m [43mim[49m[38;5;241;43m.[39;49m[43mupload_image[49m[43m([49m[43mPATH[49m[43m,[49m[43m [49m
[1;32m     31[0m [43m    [49m[43mtitle[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mtitle[49m[43m,[49m[43m [49m
[1;32m     32[0m [43m    [49m[43mdescription[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mdescription[49m[43m)[49m
[1;32m     33[0m [38;5;28mprint[39m(uploaded_image[38;5;241m.[39mtitle)
[1;32m     34[0m [38;5;28mprint[39m(uploaded_image[38;5;241m.[39mlink)

File [0;32m~/.conda/envs/work/lib/python3.9/site-packages/pyimgur/__init__.py:1150[0m, in [0;36mImgur.upload_image[0;34m(self, path, url, title, description, album)[0m
[1;32m   1145[0m     image [38;5;241m=[39m url
[1;32m   1147[0m payload [38;5;241m=[39m {[38;5;124m'[39m[38;5;124malbum_id[39m[38;5;124m'[39m: album, [38;5;124m'[39m[38;5;124mimage[39m[38;5;124m'[39m: image,
[1;32m   1148[0m            [38;5;124m'[39m[38;5;124mtitle[39m[38;5;124m'[39m: title, [38;5;124m'[39m[38;5;124mdescription[39m[38;5;124m'[39m: description}
[0;32m-> 1150[0m resp [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_request[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_base_url[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43m/3/image[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m   1151[0m [43m                          [49m[43mparams[49m[38;5;241;43m=[39;49m[43mpayload[49m[43m,[49m[43m [49m[43mmethod[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mPOST[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m   1152[0m [38;5;66;03m# TEMPORARY HACK:[39;00m
[1;32m   1153[0m [38;5;66;03m# On 5-08-2013 I noticed Imgur now returned enough information from[39;00m
[1;32m   1154[0m [38;5;66;03m# this call to fully populate the Image object. However those variables[39;00m
[1;32m   1155[0m [38;5;66;03m# that matched arguments were always None, even if they had been given.[39;00m
[1;32m   1156[0m [38;5;66;03m# See https://groups.google.com/forum/#!topic/imgur/F3uVb55TMGo[39;00m
[1;32m   1157[0m resp[[38;5;124m'[39m[38;5;124mtitle[39m[38;5;124m'[39m] [38;5;241m=[39m title

File [0;32m~/.conda/envs/work/lib/python3.9/site-packages/pyimgur/__init__.py:731[0m, in [0;36mImgur._send_request[0;34m(self, url, needs_auth, **kwargs)[0m
[1;32m    729[0m kwargs[[38;5;124m'[39m[38;5;124mauthentication[39m[38;5;124m'[39m] [38;5;241m=[39m auth
[1;32m    730[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[0;32m--> 731[0m     result [38;5;241m=[39m [43mrequest[49m[38;5;241;43m.[39;49m[43msend_request[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mverify[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mverify[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    732[0m     new_content, ratelimit_info [38;5;241m=[39m result
[1;32m    733[0m     [38;5;28;01mif[39;00m is_paginated [38;5;129;01mand[39;00m new_content [38;5;129;01mand[39;00m limit [38;5;241m>[39m [38;5;28mlen[39m(new_content):

File [0;32m~/.conda/envs/work/lib/python3.9/site-packages/pyimgur/request.py:102[0m, in [0;36msend_request[0;34m(url, params, method, data_field, authentication, verify)[0m
[1;32m    100[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m    101[0m         [38;5;28;01mpass[39;00m
[0;32m--> 102[0m     [43mresp[49m[38;5;241;43m.[39;49m[43mraise_for_status[49m[43m([49m[43m)[49m
[1;32m    103[0m ratelimit_info [38;5;241m=[39m [38;5;28mdict[39m((k, [38;5;28mint[39m(v)) [38;5;28;01mfor[39;00m (k, v) [38;5;129;01min[39;00m resp[38;5;241m.[39mheaders[38;5;241m.[39mitems()
[1;32m    104[0m                       [38;5;28;01mif[39;00m k[38;5;241m.[39mstartswith([38;5;124m'[39m[38;5;124mx-ratelimit[39m[38;5;124m'[39m))
[1;32m    105[0m [38;5;28;01mreturn[39;00m content, ratelimit_info

File [0;32m~/.conda/envs/work/lib/python3.9/site-packages/requests/models.py:960[0m, in [0;36mResponse.raise_for_status[0;34m(self)[0m
[1;32m    957[0m     http_error_msg [38;5;241m=[39m [38;5;124mu[39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m Server Error: [39m[38;5;132;01m%s[39;00m[38;5;124m for url: [39m[38;5;132;01m%s[39;00m[38;5;124m'[39m [38;5;241m%[39m ([38;5;28mself[39m[38;5;241m.[39mstatus_code, reason, [38;5;28mself[39m[38;5;241m.[39murl)
[1;32m    959[0m [38;5;28;01mif[39;00m http_error_msg:
[0;32m--> 960[0m     [38;5;28;01mraise[39;00m HTTPError(http_error_msg, response[38;5;241m=[39m[38;5;28mself[39m)

[0;31mHTTPError[0m: 400 Client Error: Bad Request for url: https://api.imgur.com/3/image
HTTPError: 400 Client Error: Bad Request for url: https://api.imgur.com/3/image

